pipeline{
    agent{
        label "node"
    }

    stages {
        stage("Stage 1") {
            steps {
                echo "Hello world"
            }
        }
    }

    

    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}