pipeline{
    agent any

    stages {
        stage("node install") {
            steps {
                script {
                    sh "docker pull node:16-alpine"
                }
            }
        }

        stage("docker images") {
            steps {
                script {
                    sh "docker images"
                }
            }
        }
    }
}